/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.is.gui;

import com.mycompany.is.gui.misc.ItemExportImportFrm;
import com.mycompany.is.gui.misc.ItemHistoryFrm;
import java.awt.Component;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author Escritorio
 */
public class Parent extends javax.swing.JFrame {
    
    ApplicationContext context;
    
    public Object getSpringBean(String name){
        return context.getBean(name);
    }
    
    /**
     * Creates new form NewJFrame
     */
    public Parent(ApplicationContext context) {
        initComponents();
        this.context = context;
    }
        
    /**
     * Creates new form NewJFrame
     */
    public Parent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        entryHistory = new javax.swing.JMenuItem();
        entryCreate = new javax.swing.JMenuItem();
        entryRetrieve = new javax.swing.JMenuItem();
        ImportExport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Inventario");

        javax.swing.GroupLayout pnDesktopLayout = new javax.swing.GroupLayout(pnDesktop);
        pnDesktop.setLayout(pnDesktopLayout);
        pnDesktopLayout.setHorizontalGroup(
            pnDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        pnDesktopLayout.setVerticalGroup(
            pnDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        entryHistory.setText("Historial");
        entryHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryHistoryActionPerformed(evt);
            }
        });
        jMenu1.add(entryHistory);

        entryCreate.setText("Gestion");
        entryCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryCreateActionPerformed(evt);
            }
        });
        jMenu1.add(entryCreate);

        entryRetrieve.setText("Retirar");
        entryRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryRetrieveActionPerformed(evt);
            }
        });
        jMenu1.add(entryRetrieve);

        ImportExport.setText("Exportar/Importar");
        ImportExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportExportActionPerformed(evt);
            }
        });
        jMenu1.add(ImportExport);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isPresent(JDesktopPane parent, Component comp){
        for (Component c : parent.getComponents()){
            if (c.equals(comp)){
                return true;
            }
        }
        return false;
    }
    
    private void addChild(JInternalFrame form){
        if (!isPresent(this.pnDesktop, form)){
            this.pnDesktop.add(form);
        }        
        form.setVisible(true);
    }
    
    private void entryHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryHistoryActionPerformed
        JInternalFrame form = ItemHistoryFrm.INSTANCE;
        this.addChild(form);
    }//GEN-LAST:event_entryHistoryActionPerformed

    private void entryCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryCreateActionPerformed
        JInternalFrame form = ItemListFrm.getInstance(this);
        this.addChild(form);
    }//GEN-LAST:event_entryCreateActionPerformed

    private void entryRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryRetrieveActionPerformed
        JInternalFrame form = ItemTakeFrm.INSTANCE;
        this.addChild(form);
    }//GEN-LAST:event_entryRetrieveActionPerformed

    private void ImportExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportExportActionPerformed
        JInternalFrame form = ItemExportImportFrm.INSTANCE;
        this.addChild(form);
    }//GEN-LAST:event_ImportExportActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ImportExport;
    private javax.swing.JMenuItem entryCreate;
    private javax.swing.JMenuItem entryHistory;
    private javax.swing.JMenuItem entryRetrieve;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane pnDesktop;
    // End of variables declaration//GEN-END:variables
}
